### ISSUE TITLE
Histogram Error

### ISSUE THREAD

**Issue by EricRoberts714** [xdatacnn/imagesearch#23]
An error using the Histogram signature occurs. I use the searching method (bf) and retrieval number (10).

![Histogram_error](https://user-images.githubusercontent.com/17167333/72117954-607e5800-3304-11ea-8e80-33ab40b2a3f0.png)

**Comment by flavio86** [comment]
Some CSV files of features from histogram method were in the output folder of the cells database. Please delete them (labels_fotf.csv, image_filenames_fotf.csv and feature_vectors_fotf.csv) and see if it works.

**Comment by EricRoberts714** [comment]
Histogram now successfully runs to completion.
