### ISSUE TITLE
Hog Error for cells = blocks = 2

### ISSUE THREAD

**Issue by EricRoberts714** [xdatacnn/imagesearch#24]
Hog signature ran to completion for cells = blocks = {3,4,5}, but an error occurs when both are set to 2.
![Hog_error](https://user-images.githubusercontent.com/17167333/72118112-fd40f580-3304-11ea-8f82-9a935d75333d.png)

**Comment by EricRoberts714** [comment]
*Update*

Cells = 2 might be the problem. The same error occurs for cells = 2, blocks = 3.

**Comment by flavio86** [comment]
The number of cells must be greater than 2. I updated the code to accept only valid values.
